[package]
name = "classgroup"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
arrayvec = "0.7.2"
hex = "0.4.2"
cpp_std = "0.1.1"
bicycl = {path = "supra-bicycl"}
miracl_core_ed25519 = "0.2.0"
miracl_core_bls12381 = "4.1.2"

#rand = {version = "0.8", features = ["rand_chacha"]}
rand_chacha = "0.2.2"
zeroize = { version = "1.4.3", features = ["zeroize_derive"] }
anyhow = "1.0.71"
serde = { version = "1.0.203", features = ["derive", "std"] }
serde_nested_with = "0.2.5"
rand = "0.8.5"


[build-dependencies.ritual_build]
git = "https://github.com/rust-qt/ritual.git"
rev = "e2b9b40f1ff57743ae0f3bf3cca43ef84545fc85"
version = "0.3.0"

[dependencies.cpp_core]
git = "https://github.com/rust-qt/ritual.git"
rev = "e2b9b40f1ff57743ae0f3bf3cca43ef84545fc85"
version = "0.5.0"
